/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ndaguan_micromanager_myCalculator */

#ifndef _Included_org_ndaguan_micromanager_myCalculator
#define _Included_org_ndaguan_micromanager_myCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    Calibration
 * Signature: (Ljava/lang/Object;[II)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ndaguan_micromanager_myCalculator_Calibration
  (JNIEnv *, jobject, jobject, jintArray, jint);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    GetForce
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_ndaguan_micromanager_myCalculator_GetForce
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    GetZPosition
 * Signature: (Ljava/lang/Object;[II)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ndaguan_micromanager_myCalculator_GetZPosition
  (JNIEnv *, jobject, jobject, jintArray, jint);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    GosseCenter
 * Signature: (Ljava/lang/Object;[I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ndaguan_micromanager_myCalculator_GosseCenter
  (JNIEnv *, jobject, jobject, jintArray,jintArray);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    DataInit
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_ndaguan_micromanager_myCalculator_DataInit
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    DeleteData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ndaguan_micromanager_myCalculator_DeleteData
  (JNIEnv *, jobject);

/*
 * Class:     org_ndaguan_micromanager_myCalculator
 * Method:    SetBitDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ndaguan_micromanager_myCalculator_SetBitDepth
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
