/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ndaguan_micromanager_Kernel */

#ifndef _Included_org_ndaguan_micromanager_Kernel
#define _Included_org_ndaguan_micromanager_Kernel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jdoubleArray JNICALL _Java_org_ndaguan_micromanager_Kernel_gosseCenter
  (JNIEnv *, jobject, jobject, jobjectArray);

JNIEXPORT jdoubleArray JNICALL _Java_org_ndaguan_micromanager_Kernel_calibration
  (JNIEnv *, jobject, jobject, jobjectArray,jint,jdouble);

JNIEXPORT jdoubleArray JNICALL _Java_org_ndaguan_micromanager_Kernel_getZPosition
  (JNIEnv *, jobject, jobject, jobjectArray);

JNIEXPORT void JNICALL _Java_org_ndaguan_micromanager_Kernel_initialize
  (JNIEnv *, jobject, jdoubleArray);
JNIEXPORT void JNICALL _Java_org_ndaguan_micromanager_Kernel_deleteRoi
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL _Java_org_ndaguan_micromanager_Kernel_releaseBuffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
